/* NEXUS v2.0 — App Controller + Router + Toast + Attachment + Doc Gen */
const Toast = (() => {
    function show(msg, type = 'info', dur = 3500) {
        const c = document.querySelector('.toast-container');
        if (!c) return;
        const t = document.createElement('div');
        t.className = `toast toast-${type}`;
        t.textContent = msg;
        c.appendChild(t);
        setTimeout(() => { t.classList.add('removing'); setTimeout(() => t.remove(), 250); }, dur);
    }
    return { show };
})();

// Document generation helper
const DocHelper = (() => {
    function downloadText(filename, content) {
        const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a'); a.href = url; a.download = filename;
        a.click(); URL.revokeObjectURL(url);
        Toast.show('📄 Document downloaded!', 'success');
    }

    function downloadHTML(filename, title, bodyHTML) {
        const html = `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>${title}</title><style>body{font-family:Arial,sans-serif;max-width:800px;margin:40px auto;padding:0 20px;color:#333;line-height:1.7}h1,h2,h3{color:#222}table{width:100%;border-collapse:collapse;margin:16px 0}th,td{padding:10px;border:1px solid #ddd;text-align:left}th{background:#f5f5f5}code{background:#f0f0f0;padding:2px 6px;border-radius:3px}pre{background:#1e1e2e;color:#e0e0e0;padding:16px;border-radius:8px;overflow-x:auto}blockquote{border-left:3px solid #4a6cf7;padding-left:16px;color:#666;font-style:italic}.footer{margin-top:40px;padding-top:16px;border-top:1px solid #eee;font-size:0.8rem;color:#999;text-align:center}</style></head><body>${bodyHTML}<div class="footer">Generated by Nexus — Developed by Prakhar</div></body></html>`;
        const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a'); a.href = url; a.download = filename;
        a.click(); URL.revokeObjectURL(url);
        Toast.show('📄 Document downloaded!', 'success');
    }

    return { downloadText, downloadHTML };
})();

// File attachment manager
const Attachment = (() => {
    let currentFile = null;
    let currentBase64 = null;

    function init() {
        const attachBtn = document.getElementById('attach-btn');
        const fileInput = document.getElementById('file-input');
        const preview = document.getElementById('attach-preview');
        const thumb = document.getElementById('attach-thumb');
        const info = document.getElementById('attach-info');
        const removeBtn = document.getElementById('attach-remove');

        if (!attachBtn || !fileInput) return;

        attachBtn.addEventListener('click', () => fileInput.click());

        fileInput.addEventListener('change', (e) => {
            const file = e.target.files[0];
            if (!file) return;
            currentFile = file;

            if (file.type.startsWith('image/')) {
                const reader = new FileReader();
                reader.onload = (ev) => {
                    currentBase64 = ev.target.result;
                    thumb.src = ev.target.result;
                    thumb.style.display = 'block';
                    info.textContent = `📎 ${file.name} (${(file.size/1024).toFixed(1)} KB)`;
                    preview.classList.add('active');
                };
                reader.readAsDataURL(file);
            } else {
                thumb.style.display = 'none';
                info.textContent = `📎 ${file.name} (${(file.size/1024).toFixed(1)} KB)`;
                preview.classList.add('active');
                if (file.type.startsWith('text/') || file.name.endsWith('.txt') || file.name.endsWith('.csv')) {
                    const reader = new FileReader();
                    reader.onload = (ev) => { currentBase64 = ev.target.result; };
                    reader.readAsText(file);
                }
            }
            Toast.show(`📎 ${file.name} attached`, 'success');
            document.getElementById('send-btn').disabled = false;
        });

        removeBtn?.addEventListener('click', () => clear());
    }

    function clear() {
        currentFile = null; currentBase64 = null;
        const preview = document.getElementById('attach-preview');
        if (preview) preview.classList.remove('active');
        const fileInput = document.getElementById('file-input');
        if (fileInput) fileInput.value = '';
    }

    function getAttachmentContext() {
        if (!currentFile) return '';
        let ctx = `[User attached: "${currentFile.name}" (${currentFile.type}, ${(currentFile.size/1024).toFixed(1)} KB)]`;
        if (currentBase64 && typeof currentBase64 === 'string' && !currentBase64.startsWith('data:image')) {
            ctx += '\n\nFile contents:\n' + currentBase64.substring(0, 5000);
        }
        if (currentFile.type.startsWith('image/')) {
            ctx += '\n[This is an image. Acknowledge receipt and ask what to do with it.]';
        }
        return ctx;
    }

    function hasAttachment() { return !!currentFile; }
    return { init, clear, getAttachmentContext, hasAttachment };
})();

const Router = (() => {
    let current = 'chat';
    function go(featureId) {
        document.querySelectorAll('.feature-panel').forEach(p => p.classList.remove('active'));
        const panel = document.getElementById('panel-' + featureId);
        if (panel) panel.classList.add('active');
        document.querySelectorAll('.fnav-item').forEach(n => n.classList.remove('active'));
        const navItem = document.querySelector(`.fnav-item[data-feature="${featureId}"]`);
        if (navItem) navItem.classList.add('active');
        current = featureId;
        Features.initFeature(featureId);
    }
    function getCurrent() { return current; }
    return { go, getCurrent };
})();

const App = (() => {
    function init() {
        Preloader.init();
        setTimeout(() => {
            Settings.init();
            setupNav();
            setupVoice();
            setupKeyboard();
            Attachment.init();
            Chat.init();
            Router.go('chat');
            Settings.applyTheme();
        }, 100);
    }

    function setupNav() {
        document.querySelectorAll('.fnav-item').forEach(item => {
            item.addEventListener('click', () => {
                const feature = item.dataset.feature;
                if (feature) Router.go(feature);
            });
        });
        const toggle = document.getElementById('sidebar-toggle');
        const sidebar = document.querySelector('.sidebar');
        if (toggle && sidebar) toggle.addEventListener('click', () => sidebar.classList.toggle('open'));
        document.getElementById('settings-btn')?.addEventListener('click', () => Settings.open());
        document.getElementById('header-settings-btn')?.addEventListener('click', () => Settings.open());
    }

    function setupVoice() {
        const micBtn = document.getElementById('mic-btn');
        const stopBtn = document.getElementById('stop-speak-btn');
        const waveform = document.querySelector('.voice-waveform');
        const speakLabel = document.querySelector('.speaking-label');

        Voice.setOnTranscript(text => {
            const preview = document.querySelector('.voice-preview');
            if (preview) { preview.textContent = text; preview.classList.add('active'); }
        });
        Voice.setOnFinalTranscript(text => {
            const input = document.getElementById('chat-input');
            if (input) { input.value = text; input.dispatchEvent(new Event('input')); }
            const preview = document.querySelector('.voice-preview');
            if (preview) { preview.classList.remove('active'); preview.textContent = ''; }
            setTimeout(() => Chat.handleSend(), 300);
        });
        Voice.setOnListeningChange(l => { if (micBtn) micBtn.classList.toggle('listening', l); });
        Voice.setOnSpeakingChange(s => {
            if (waveform) waveform.classList.toggle('active', s);
            if (speakLabel) speakLabel.classList.toggle('active', s);
            if (stopBtn) stopBtn.classList.toggle('active', s);
        });
        micBtn?.addEventListener('click', () => Voice.toggleListening());
        stopBtn?.addEventListener('click', () => Voice.stopSpeaking());
        if (micBtn && !Voice.isSupported()) micBtn.style.display = 'none';
    }

    function setupKeyboard() {
        document.addEventListener('keydown', e => {
            if (e.key === 'Escape') { Settings.close(); Voice.stopSpeaking(); }
            if (e.ctrlKey && e.key === 'm') { e.preventDefault(); Voice.toggleListening(); }
            if (e.ctrlKey && e.key === 'n') { e.preventDefault(); Chat.newChat(); Router.go('chat'); }
        });
    }

    return { init };
})();

document.addEventListener('DOMContentLoaded', () => App.init());
